language: go
dist: bionic

go:
  - 1.13.x

cache:
  directories:
    - $GOPATH/src

before_install:
  - cd app

install:
  - go get -d ./...

jobs:
  include:
    - name: Gofmt check
      stage: build
      script: ../.travis.gofmt.sh
    - name: Go build
      stage: build
      script: go build ./...

stages:
  - build

branches:
  except:
    - /^exp-.*$/
