language: go
dist: bionic

go:
  - 1.13.x

cache:
  directories:
    - $GOPATH/src

before_script:
  - cd app

install:
  - go get -d ./...

jobs:
  include:
    - name: Gofmt check
      script: go fmt ./...
    - name: Go build
      script: go build ./...

branches:
  except:
    - /^exp-.*$/
