language: go
dist: bionic

go:
  - 1.13.x

before_install:
  - cd app
  - ls -l

install:
  - go get -d ./...
  - ls -l

jobs:
  include:
    - name: Go build
      stage: build
      script:
        - ls -l
        - go fmt ./...
        - go build -v ./...

stages:
  - build

branches:
  except:
    - /^exp-.*$/
