language: go

go:
  - 1.13.x

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - cd app

jobs:
  include:
    - name: Gofmt check
      script: go fmt ./...
    - name: Go build
      script: go build ./...

branches:
  except:
    - /^exp-.*$/
